#!/bin/bash
# ============================================================================
#  fail2ban.sh — fail2ban as the second layer (brute-force, incl. in-country).
#
#  - Configures the [asterisk] jail in jail.local.
#  - Writes jail.d/zz-sip-shield.local so loopback, trunks and trusted IPs are
#    never banned by ANY jail (read last, so it wins over jail.d/*.conf).
#  - Wires a ban-logging action that also feeds the observability layer.
#  - Optionally pre-bans a known-bad IP list from lib/known-ips.txt.
# ============================================================================

LOG_FILE="/var/log/sip-shield.log"

log_ban() {
    local ip="$1" origin="${2:-manual}"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] BAN ip=$ip origin=$origin" >> "$LOG_FILE"
    # Additive observability hook (JSON log + webhook). No-op if not configured.
    record_event "ban" "$ip" "$origin" 2>/dev/null || true
}

configure_fail2ban() {
    local logpath jail=/etc/fail2ban/jail.local tmp changed=0
    logpath=$(detect_asterisk_logpath)
    echo "[*] Configuring fail2ban asterisk jail..."

    if [ ! -f "$logpath" ]; then
        touch "$logpath"
        chown asterisk:asterisk "$logpath" 2>/dev/null || true
        asterisk -rx "logger reload" > /dev/null 2>&1 || true
    fi

    setup_ban_action && changed=1

    touch "$jail"
    tmp=$(mktemp)
    # Keep everything else in jail.local, replacing only the [asterisk] section.
    awk '/^\[/{skip=($0=="[asterisk]")} !skip' "$jail" | sed -e :a -e '/^\n*$/{$d;N;ba' -e '}' > "$tmp"
    # Explicit ignoreip WITHOUT 127.0.0.1 stripped: some distros' jail.d/*.conf
    # set ignoreip per jail, overriding [DEFAULT]; we repeat it here too.
    cat >> "$tmp" << EOJ

[asterisk]
enabled = true
ignoreip = $(echo "127.0.0.1/8 ::1 $TRUNK_IPS $TRUSTED_IPS $F2B_IGNORE_IPS" | xargs)
logpath = ${logpath}
maxretry = ${SIP_SHIELD_MAXRETRY}
findtime = ${SIP_SHIELD_FINDTIME}
bantime = ${SIP_SHIELD_BANTIME}
action = %(action_mwl)s
         sip-shield-log
EOJ
    if ! cmp -s "$tmp" "$jail"; then
        cp -a "$jail" "$jail.bak.$(date +%Y%m%d%H%M%S)"
        cat "$tmp" > "$jail"
        changed=1
    fi
    rm -f "$tmp"

    write_protected_ips_conf && changed=1

    if ! systemctl is-active --quiet fail2ban; then
        systemctl enable fail2ban > /dev/null 2>&1
        systemctl restart fail2ban
        sleep 2
    elif [ "$changed" = 1 ]; then
        fail2ban-client reload > /dev/null 2>&1 || systemctl restart fail2ban
        sleep 2
    fi
    if systemctl is-active --quiet fail2ban; then
        echo "[+] fail2ban active (asterisk jail: bantime $((SIP_SHIELD_BANTIME / 86400)) days, maxretry ${SIP_SHIELD_MAXRETRY})"
    else
        echo "[!] fail2ban did not start:"
        journalctl -u fail2ban -n 10 --no-pager
        return 1
    fi
    unban_protected_ips
    ban_known_ips
}

# Make every jail (Issabel's and ours) ignore loopback, trunks and trusted IPs.
# jail.d/*.local is read last by fail2ban, so this wins. Returns 0 if it changed.
write_protected_ips_conf() {
    local f=/etc/fail2ban/jail.d/zz-sip-shield.local tmp jails j ign
    ign=$(echo "127.0.0.1/8 ::1 $TRUNK_IPS $TRUSTED_IPS $F2B_IGNORE_IPS" | xargs)
    jails=$( {
        fail2ban-client status 2>/dev/null | sed -n 's/.*Jail list:[[:space:]]*//p' | tr ',' '\n'
        grep -hoE '^\[[^]]+\]' /etc/fail2ban/jail.local /etc/fail2ban/jail.d/*.conf 2>/dev/null | tr -d '[]'
        echo asterisk
    } | tr -d ' \r\t' | grep -vxE 'DEFAULT|INCLUDES|Definition|Init|' | sort -u)
    tmp=$(mktemp)
    {
        echo "# Generated by SIP Shield — these IPs are NEVER banned by any jail."
        echo "# To change, edit TRUNK_IPS/TRUSTED_IPS/F2B_IGNORE_IPS in $CONF_FILE"
        printf '[DEFAULT]\nignoreip = %s\n' "$ign"
        for j in $jails; do printf '\n[%s]\nignoreip = %s\n' "$j" "$ign"; done
    } > "$tmp"
    if cmp -s "$tmp" "$f"; then rm -f "$tmp"; return 1; fi
    mkdir -p /etc/fail2ban/jail.d
    mv -f "$tmp" "$f"; chmod 644 "$f"
    echo "[+] ignoreip for loopback/trunks/trusted applied to all jails ($f)"
    return 0
}

# Ensure trunks/trusted aren't banned anywhere.
unban_protected_ips() {
    local ip j rule jails
    jails=$(fail2ban-client status 2>/dev/null | sed -n 's/.*Jail list:[[:space:]]*//p' | tr ',' ' ')
    for ip in $TRUNK_IPS $TRUSTED_IPS $F2B_IGNORE_IPS; do
        [ -z "$ip" ] && continue
        fail2ban-client unban "$ip" > /dev/null 2>&1
        for j in $jails; do fail2ban-client set "$j" unbanip "$ip" > /dev/null 2>&1; done
        iptables -S 2>/dev/null | grep -E "^-A (f2b-|F2B_)[^ ]* -s ${ip//./\\.}/32 .*-j (REJECT|DROP)" \
            | while IFS= read -r rule; do eval "iptables -D ${rule#-A }" 2>/dev/null; done
    done
}

# Ban-logging action. Also calls record-event.sh so bans reach the JSON log and
# webhook even though fail2ban actions run as plain shell (they don't source us).
setup_ban_action() {
    local f=/etc/fail2ban/action.d/sip-shield-log.conf tmp
    tmp=$(mktemp)
    cat > "$tmp" << EOA
[Definition]
actionban = echo "[\$(date '+%%Y-%%m-%%d %%H:%%M:%%S')] BAN ip=<ip> origin=fail2ban jail=<name>" >> /var/log/sip-shield.log; bash ${INSTALL_DIR}/lib/record-event.sh ban <ip> fail2ban >/dev/null 2>&1 || true
actionunban = echo "[\$(date '+%%Y-%%m-%%d %%H:%%M:%%S')] UNBAN ip=<ip> origin=fail2ban jail=<name>" >> /var/log/sip-shield.log; bash ${INSTALL_DIR}/lib/record-event.sh unban <ip> fail2ban >/dev/null 2>&1 || true
EOA
    if cmp -s "$tmp" "$f"; then rm -f "$tmp"; return 1; fi
    mv -f "$tmp" "$f"; chmod 644 "$f"
    return 0
}

# Optional pre-ban of a known-bad IP list from a file (see known-ips.txt.example).
ban_known_ips() {
    if [ ! -f "$SIP_SHIELD_KNOWN_IPS_FILE" ]; then
        echo "[*] No known-ips file at $SIP_SHIELD_KNOWN_IPS_FILE, skipping pre-ban."
        echo "    (copy lib/known-ips.txt.example to lib/known-ips.txt to enable)"
        return 0
    fi
    echo "[*] Pre-banning known attacker IPs from $SIP_SHIELD_KNOWN_IPS_FILE..."
    local banned ip n=0
    banned=$(fail2ban-client status asterisk 2>/dev/null | grep 'Banned IP list')
    while IFS= read -r ip; do
        [[ -z "$ip" || "$ip" == \#* ]] && continue
        echo " $TRUNK_IPS $TRUSTED_IPS $F2B_IGNORE_IPS " | grep -q " $ip " && continue
        echo "$banned" | grep -qw "$ip" && continue
        if fail2ban-client set asterisk banip "$ip" > /dev/null 2>&1; then
            log_ban "$ip" "known-ips-list"; n=$((n + 1))
        fi
    done < "$SIP_SHIELD_KNOWN_IPS_FILE"
    echo "[+] ${n} IPs pre-banned"
}
